### ISSUE TITLE
Username and password 

### ISSUE THREAD

**Issue by gerhard1951** [tillsteinbach/WeConnect-cli#103]
Hi,
during my log-in problems yesterday I found out that neither the rigth username nor the right password is necessary to get access via weconnect-cli to the myvolkswagen API. Only a placeholder for both ist necessary. A single random character for username and password is sufficient. Modifying the vehicle number denies the access.
What is the reason behind it? I tested it with a commandline interpreter with the following command:

weconnect-cli --username mail@XXXXXXXXX.de --password YYYYYYYYYY get /vehicles/WVWZZZZZZZZZZZZZZ/domains/charging/batteryStatus/currentSOC_pct

**Comment by tillsteinbach** [comment]
Ok, this is more complex. So I give you some background:
- WeConnect-cli is caching the responses from the server between calls. This is to avoid people spamming the VW servers with a lot of requests. The cache file is stored on your hard disk. If you don't want this behaviour you can turn it off with `--no-cache`. But take care that VW is not locking you out due to too many requests.
- Still when you disable the caching with `--no-cache` you will see the behaviour you are observing. VW is using oauth. The username and password is only necessary to get a token. This token is valid for 60minutes. After that the token is refreshed. I also store the token on the hard drive to prevent unnecessary logins for each call. So if the last call to weconnect-cli was within 60minutes you will not see a new login. The token is just reused. You can disable that feature with `--no-token-storage`. But as a consequence every call to weconnect-cli will cause a new login first.
I hope this clears the situation up.

**Comment by gerhard1951** [comment]
Thank you for the immediate and perfect explanation. I understand your access strategy and appreciate the preventing from too many requests. In other API accesses I had to take care of it by myself.
